### ISSUE TITLE
Explore if inject is necessary at this point

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-node#12]

**Comment by kriskowal** [comment]
I’ve greatly reduced the use of this injection pattern in the #15 rewrite, but I think this is still an open topic. @abhinav has recommended a less RPC-centric dependency injection pattern, where the user would construct RPC and other dependencies and explicitly call "inject()" with the the application object (an object containing all of the application scope dependencies by conventional names like "logger", "stats", "tracer", "dispatcher"). In the rewrite, I backed away from exposing injection to the RPC user and the RPC constructor just injects dependencies into the objects it owns: inbounds, outbounds, dispatcher, &c. I could be convinced either way.
