### ISSUE TITLE
Move towards the Top-Level Req/Res Objects approach.

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-node#14]
Current winning proposal is Top-Level Request/Response Object - this approach has ergonomic in/out symmetry and separates metadata that propagates (context) from regular req/res metadata.

```
res = handler(Request(service..., procedure..., body=..., headers=..., context=...,)

print res.body, res.headers, res.context
```

Properties in the context will be propagated/ while properties on the req/res will not.

Let's move towards this in all our Non-Go codebases.

**Comment by kriskowal** [comment]
To be fixed in #15 rewrite
