### ISSUE TITLE
Settle on request and response wrapper RW interface for all encodings.

### ISSUE THREAD

**Issue by kriskowal** [yarpc/yarpc-node#21]
I’ve increasingly nervous about the coupling between this project and ThriftRW since I have been avoiding the creation of wrappers around argument and result structs for request and response bodies. The toBufferResult/fromBufferResult interface in the current incarnation is temporary. We will need to create an RW that accepts the entire request and response instead of focusing on the body, in order to support #18 Thrift Envelopes, so a wrapper is inevitable.

**Comment by breerly** [comment]
We reached a similar conclusion in yarpc-python.

:+1:
